### ISSUE TITLE
Invitation to collaborate

### ISSUE THREAD

**Issue by jzabroski** [sharpmigrations/sharpmigrations#19]
@andrecarlucci I see that you are running a project similar to our own, [FluentMigrator](https://github.com/fluentmigrator/fluentmigrator).  We are getting very close to mechanizing a great deal of our infrastructure using Azue DevOps and Docker-in-Docker to run integration tests against all the database providers we support.  We also support a lot more features.  It would be great to have you as a combined collaborator as opposed to a "competitor".

Frankly, I did not know this project existed until I saw Oren Novotny's recent change from Regional Director to Program Manager at Microsoft and went through list of other Regional Directors and your name came up.

What do you think?  Better to spread cream cheese thick than thin?  You can be the lox on our bagel :)

**Comment by andrecarlucci** [comment]
Hi @jzabroski 
Interesting time you ask. We are just planning to standardize a bit our database migrations projects here at the bank. It's being a long time since I touched sharpmigration's code (well, it works) and we were checking if it was worth it to improve the code or maybe check FluentMigration or other frameworks.
It would be an honor and way more fun to collaborate with you guys instead, please, let me know how could we proceed :)

**Comment by andrecarlucci** [comment]
Actually, sorry about the dates, I somehow missed your first comment and just read the second message, which was actually you closing the ticket.

**Comment by jzabroski** [comment]
@andrecarlucci Still welcome to have your help.

FluentMigrator is pretty mature.  The main holes I see are there are a few bugs in MySQL Generator owing to the fact that there are so many permutations of MySQL out there (e.g., MariaDB).  I've tried to tag all the issues as much as possible so it's obvious what the problems are.

If you use SQL Server, there is no doubt in my mind you want to use FluentMigrator.

Happy to help you get started.
